### ISSUE TITLE
Tracking Sinks

### ISSUE THREAD

**Issue by mdewey131** [Snappametrics/Snappa-Scoreboard#32]
Now that we record whether or not there was a clink, we have the ability to see whether or not a sink has been recorded on three point shots. We can add functionality to the app to ask who was sunk when the app suspects there has been a sink. 

In the backend, we can add columns to career stats to support stat tracking and tell players how many times they've been sunk

**Comment by MokeEire** [comment]
Think you did this somewhere?

**Comment by MokeEire** [comment]
This was done ages ago!
